export { bsuirClient } from "./bsuir-client";
export { getBsuirErrorMessage } from "./bsuir-error";
export type {
  Announcement,
  ApiDateResponse,
  Auditory,
  AuditoryDepartment,
  AuditoryType,
  BsuirClient,
  BsuirClientOptions,
  BuildingNumber,
  CacheOptions,
  ClientHooks,
  Department,
  EducationForm,
  Employee,
  EmployeeCatalogItem,
  ErrorHookContext,
  Faculty,
  FlattenedLessonsByDay,
  FlattenedScheduleItem,
  LessonStudentGroup,
  Maybe,
  NormalizedScheduleResponse,
  ReadOptions,
  RequestHookContext,
  RequestOptions,
  ResponseHookContext,
  RetryHookContext,
  ScheduleFilterOptions,
  ScheduleItem,
  ScheduleResponse,
  Speciality,
  StudentGroupCatalogItem,
  StudentGroupShort,
  Weekday,
  WeekScheduleMap,
} from "./bsuir-types";
export {
  BsuirApiError,
  BsuirConfigurationError,
  BsuirNetworkError,
  BsuirResponseValidationError,
  BsuirTimeoutError,
  BsuirValidationError,
} from "bsuir-iis-api";
